"""CSL 脚本通用常量。"""

MATCH_EXACT = "exact"
MATCH_CONTAINS = "contains"
MATCH_LIST_EXACT = "list_exact"
MATCH_NOT_CONTAINS = "not_contains"
MATCH_NOT_EMPTY = "not_empty"

DEFAULT_DOCTOR_RANK = "主任医师"
DEFAULT_INVALID_FOCUS_INPUT = "不知道"
DEFAULT_DEPARTMENT = "ICU"

FOCUS_BRANCH_F1 = "F1"
FOCUS_BRANCH_F2_OPTION = "F2_OPTION"
FOCUS_BRANCH_F2_CUSTOM = "F2_CUSTOM"
FOCUS_BRANCH_F3 = "F3"
FOCUS_BRANCHES = {
    FOCUS_BRANCH_F1,
    FOCUS_BRANCH_F2_OPTION,
    FOCUS_BRANCH_F2_CUSTOM,
    FOCUS_BRANCH_F3,
}
